sudo: required
services:
  - docker

before_install:
  - docker build -t zelucaspiprecipes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run zelucaspiprecipes/react-test npm test -- --coverage

after_success:  
  - docker build -t zelucaspiprecipes/multi-client ./client
  - docker build -t zelucaspiprecipes/multi-nginx ./nginx
  - docker build -t zelucaspiprecipes/multi-server ./server
  - docker build -t zelucaspiprecipes/multi-worker ./worker
  # Login into ti the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push then into docker hub
  - docker push zelucaspiprecipes/multi-client
  - docker push zelucaspiprecipes/multi-nginx
  - docker push zelucaspiprecipes/multi-server
  - docker push zelucaspiprecipes/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-485970711081
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
